# requires nightly rust to be installed for formatting

edition = "2021"
unstable_features = true

use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_macro_matchers = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# make max line length load
fn_call_width = 150